version: '3.8'

services:
    webapp:
        restart: always
        build:
            context: "./webapp/"
            dockerfile: dockerfile
        #command: python manage.py run -h 0.0.0.0       
        networks:
            - webappnet
        #ports:
        #   - 8000:8000
        expose:
            - 8000
        deploy: 
            mode: replicated
            replicas: 4   
            endpoint_mode: vip 
    
    nginx:
        restart: always
        build:
            context: "./nginx/"
            dockerfile: dockerfile
        #command: python manage.py run -h 0.0.0.0       
        networks:
            - webappnet
        ports:
            - 80:80  
        depends_on:
            - webapp

networks:
    webappnet:
        driver: bridge 

